### ISSUE TITLE
Cannot navigate down into directory hierarchy

### ISSUE THREAD

**Issue by dgiglio** [bjesus/tidalfs#1]
Hi,
I've tried to run your project and if I browse down further the first level I always see the same directories:

````
$ ls Artist
A  B  C  D  E  F  G  H  I  J  K  L  M  N  O  P  Q  R  S  T  U  V  W  X  Y  Z
$ ls Artist/A
A  B  C  D  E  F  G  H  I  J  K  L  M  N  O  P  Q  R  S  Search  Space  T  U  V  W  X  Y  Z
````

It's the same for every directory I try.

**Comment by bjesus** [comment]
This is intentional - since TidalFS was originally built to be used in Home Assistant's Media Browser, where one cannot create directories - this is how you search on TidalFS. For example, to search for the beatles you would navigate to "Artist/B/E/A/T/L/E/S/Search"
